Repository crc-org/vfkit, pull requests merged in 2024-08, with the labels that each got.

#110 Add Praveen to OWNERS
  OWNERS
Labels: lgtm

#179 Add readonly option for storage devices
  doc/usage.md
  pkg/config/json_test.go
  pkg/config/virtio.go
  pkg/config/virtio_test.go
Labels: lgtm, approved, needs-ok-to-test

#148 Add support for running macOS guests.
  .gitignore
  README.md
  cmd/vfkit/root.go
  doc/quickstart.md
  doc/usage.md
  pkg/config/bootloader.go
  pkg/vf/bootloader.go
  pkg/vf/virtio.go
  pkg/vf/vm.go
  pkg/vf/vm_amd64.go
  pkg/vf/vm_arm64.go
Labels: lgtm, approved, ok-to-test

#185 Fix linting issues
  .github/workflows/compile.yml
  cmd/vfkit/timesync.go
  pkg/config/config.go
  pkg/config/json_test.go
  pkg/config/virtio.go
  pkg/vf/virtio.go
  pkg/vf/virtionet.go
  pkg/vf/vsock.go
  test/osprovider.go
  test/vm_helpers.go
  tools/go.mod
  tools/go.sum
Labels: lgtm, approved

#181 doc: Fix recently reported issues
  doc/usage.md
Labels: approved
