Repository crc-org/vfkit, pull requests merged in 2024-01, with the labels that each got.

#76 virtio: Enable full disk caching
  pkg/vf/virtio.go
Labels: lgtm, ok-to-test

#77 tree-wide: Lowercase error strings
  pkg/config/bootloader.go
  pkg/config/config.go
  pkg/config/virtio.go
Labels: lgtm, approved, needs-ok-to-test

#87 Revert "ghactions: Add snyk code scanning"
  .github/workflows/snyk.yml
Labels: lgtm, approved

#74 refactor(vsock): call proxy.Close when vm stop
  cmd/vfkit/main.go
  pkg/vf/vsock.go
Labels: lgtm, approved, ok-to-test

#78 Add support for nvme devices
  doc/usage.md
  pkg/config/json.go
  pkg/config/virtio.go
  pkg/config/virtio_test.go
  pkg/vf/virtio.go
Labels: lgtm, approved, ok-to-test

#89 feat(config): add AddDevices function
  pkg/config/config.go
  pkg/config/json_test.go
Labels: lgtm, approved, ok-to-test

#90 refactor: improve function comments
  pkg/config/virtio.go
  pkg/rest/vf/vm_config.go
Labels: lgtm, approved, ok-to-test
